### ISSUE TITLE
SparkJson/SparkJson.h: No such file or directory

### ISSUE THREAD

**Issue by rathodpriyank** [charifmahmoudi/getstructure-particle#1]
Veryfing code using this library in Particle Build fails with this error:

```
Structure-MQTT-device/Structure-MQTT-device.h:38:33: fatal error: SparkJson/SparkJson.h: No such file or directory
 #include "SparkJson/SparkJson.h"
                                 ^
```

**Comment by charifmahmoudi** [comment]
Hello,
You need to add the library SparkJson to your project.
Just search for SparkJson on the community libraries and add it. That will fix your problem.
I did not include the SparkJson source code on this library to be able to use any bugfix on new feature added to the SparkJson library.

Please let me know if that fix your problem. I will wait for your feedback and update the readme to be more explicit about the dependencies before closing this issue..
